//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JinwooMin.RichBrowserControl.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JinwooMin.RichBrowserControl.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap about_16 {
            get {
                object obj = ResourceManager.GetObject("about_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap back_16 {
            get {
                object obj = ResourceManager.GetObject("back_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Cancel {
            get {
                object obj = ResourceManager.GetObject("Cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cancl_16 {
            get {
                object obj = ResourceManager.GetObject("cancl_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Close {
            get {
                object obj = ResourceManager.GetObject("Close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Document {
            get {
                object obj = ResourceManager.GetObject("Document", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Document__Add_ {
            get {
                object obj = ResourceManager.GetObject("Document__Add_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Folder__Add_ {
            get {
                object obj = ResourceManager.GetObject("Folder__Add_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap forwd_16 {
            get {
                object obj = ResourceManager.GetObject("forwd_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Help__Alt_3_ {
            get {
                object obj = ResourceManager.GetObject("Help__Alt_3_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Help__Edit_ {
            get {
                object obj = ResourceManager.GetObject("Help__Edit_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap help_16 {
            get {
                object obj = ResourceManager.GetObject("help_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Home {
            get {
                object obj = ResourceManager.GetObject("Home", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Home__Alt_2_ {
            get {
                object obj = ResourceManager.GetObject("Home__Alt_2_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap home_16 {
            get {
                object obj = ResourceManager.GetObject("home_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Information {
            get {
                object obj = ResourceManager.GetObject("Information", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A&amp;ddress.
        /// </summary>
        internal static string LABEL_ADDRESS {
            get {
                return ResourceManager.GetString("LABEL_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string LABEL_BACK {
            get {
                return ResourceManager.GetString("LABEL_BACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cloase.
        /// </summary>
        internal static string LABEL_CLOSE_TAB {
            get {
                return ResourceManager.GetString("LABEL_CLOSE_TAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward.
        /// </summary>
        internal static string LABEL_FORWARD {
            get {
                return ResourceManager.GetString("LABEL_FORWARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        internal static string LABEL_GO {
            get {
                return ResourceManager.GetString("LABEL_GO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string LABEL_HOME {
            get {
                return ResourceManager.GetString("LABEL_HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string LABEL_INFORMATION {
            get {
                return ResourceManager.GetString("LABEL_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string LABEL_LOADING {
            get {
                return ResourceManager.GetString("LABEL_LOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string LABEL_NEW {
            get {
                return ResourceManager.GetString("LABEL_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string LABEL_REFRESH {
            get {
                return ResourceManager.GetString("LABEL_REFRESH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string LABEL_STOP {
            get {
                return ResourceManager.GetString("LABEL_STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab.
        /// </summary>
        internal static string LABEL_TAB {
            get {
                return ResourceManager.GetString("LABEL_TAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web.
        /// </summary>
        internal static string LABEL_WEB {
            get {
                return ResourceManager.GetString("LABEL_WEB", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Left {
            get {
                object obj = ResourceManager.GetObject("Left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Address.
        /// </summary>
        internal static string MENU_ADDRESS {
            get {
                return ResourceManager.GetString("MENU_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Tab.
        /// </summary>
        internal static string MENU_CLOSE_TAB {
            get {
                return ResourceManager.GetString("MENU_CLOSE_TAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&amp;xit.
        /// </summary>
        internal static string MENU_EXIT {
            get {
                return ResourceManager.GetString("MENU_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;File.
        /// </summary>
        internal static string MENU_FILE {
            get {
                return ResourceManager.GetString("MENU_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Help.
        /// </summary>
        internal static string MENU_HELP {
            get {
                return ResourceManager.GetString("MENU_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string MENU_INFORMATION {
            get {
                return ResourceManager.GetString("MENU_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Tab.
        /// </summary>
        internal static string MENU_NEXT_TAB {
            get {
                return ResourceManager.GetString("MENU_NEXT_TAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Options....
        /// </summary>
        internal static string MENU_OPTIONS {
            get {
                return ResourceManager.GetString("MENU_OPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previouse Tab.
        /// </summary>
        internal static string MENU_PREV_TAB {
            get {
                return ResourceManager.GetString("MENU_PREV_TAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Tab.
        /// </summary>
        internal static string MENU_TAB {
            get {
                return ResourceManager.GetString("MENU_TAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Toolbars.
        /// </summary>
        internal static string MENU_TOOLBARS {
            get {
                return ResourceManager.GetString("MENU_TOOLBARS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Tools.
        /// </summary>
        internal static string MENU_TOOLS {
            get {
                return ResourceManager.GetString("MENU_TOOLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;View.
        /// </summary>
        internal static string MENU_VIEW {
            get {
                return ResourceManager.GetString("MENU_VIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Web.
        /// </summary>
        internal static string MENU_WEB {
            get {
                return ResourceManager.GetString("MENU_WEB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found plugin: {0}.
        /// </summary>
        internal static string MSG_FOUND_PLUGIN {
            get {
                return ResourceManager.GetString("MSG_FOUND_PLUGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialized..
        /// </summary>
        internal static string MSG_INITED_PLUGIN {
            get {
                return ResourceManager.GetString("MSG_INITED_PLUGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing....
        /// </summary>
        internal static string MSG_INITING_PLUGIN {
            get {
                return ResourceManager.GetString("MSG_INITING_PLUGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RichBrowserPlatform finished..
        /// </summary>
        internal static string MSG_RBP_FINISHED {
            get {
                return ResourceManager.GetString("MSG_RBP_FINISHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RichBrowserPlatform finishing....
        /// </summary>
        internal static string MSG_RBP_FINISHING {
            get {
                return ResourceManager.GetString("MSG_RBP_FINISHING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RichBrowserPlatform finishing canceled..
        /// </summary>
        internal static string MSG_RBP_FINISHING_CANCELED {
            get {
                return ResourceManager.GetString("MSG_RBP_FINISHING_CANCELED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RichBrowserPlatform started..
        /// </summary>
        internal static string MSG_RBP_STARTED {
            get {
                return ResourceManager.GetString("MSG_RBP_STARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RichBrowserPlatform starting....
        /// </summary>
        internal static string MSG_RBP_STARTING {
            get {
                return ResourceManager.GetString("MSG_RBP_STARTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string MSG_READY {
            get {
                return ResourceManager.GetString("MSG_READY", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap new_16 {
            get {
                object obj = ResourceManager.GetObject("new_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Play {
            get {
                object obj = ResourceManager.GetObject("Play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ref_16 {
            get {
                object obj = ResourceManager.GetObject("ref_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Refresh {
            get {
                object obj = ResourceManager.GetObject("Refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Right {
            get {
                object obj = ResourceManager.GetObject("Right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap save_16 {
            get {
                object obj = ResourceManager.GetObject("save_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Search {
            get {
                object obj = ResourceManager.GetObject("Search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Star {
            get {
                object obj = ResourceManager.GetObject("Star", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap stop_16 {
            get {
                object obj = ResourceManager.GetObject("stop_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
