//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JinwooMin.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JinwooMin.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alpha.
        /// </summary>
        internal static string LABEL_ALPHA {
            get {
                return ResourceManager.GetString("LABEL_ALPHA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to beta.
        /// </summary>
        internal static string LABEL_BETA {
            get {
                return ResourceManager.GetString("LABEL_BETA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to build.
        /// </summary>
        internal static string LABEL_BUILD {
            get {
                return ResourceManager.GetString("LABEL_BUILD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        internal static string LABEL_CANCEL {
            get {
                return ResourceManager.GetString("LABEL_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading....
        /// </summary>
        internal static string LABEL_DOWNLOADING {
            get {
                return ResourceManager.GetString("LABEL_DOWNLOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string LABEL_ERROR {
            get {
                return ResourceManager.GetString("LABEL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to patch.
        /// </summary>
        internal static string LABEL_PATCH {
            get {
                return ResourceManager.GetString("LABEL_PATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string LABEL_QUESTION {
            get {
                return ResourceManager.GetString("LABEL_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rc.
        /// </summary>
        internal static string LABEL_RC {
            get {
                return ResourceManager.GetString("LABEL_RC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is aleady running..
        /// </summary>
        internal static string MSG_ALREADY_RUNNING {
            get {
                return ResourceManager.GetString("MSG_ALREADY_RUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed..
        /// </summary>
        internal static string MSG_COMPLETED {
            get {
                return ResourceManager.GetString("MSG_COMPLETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting... (Skip in {0}sec.).
        /// </summary>
        internal static string MSG_CONNECTING {
            get {
                return ResourceManager.GetString("MSG_CONNECTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading...{0} ({1}%).
        /// </summary>
        internal static string MSG_DOWNLOADED {
            get {
                return ResourceManager.GetString("MSG_DOWNLOADED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version &apos;{0} {1}&apos; is here. Do you want to upgrade?.
        /// </summary>
        internal static string MSG_NEW_VERSION_HERE {
            get {
                return ResourceManager.GetString("MSG_NEW_VERSION_HERE", resourceCulture);
            }
        }
    }
}
